export const characters = {
  ironman: {
    id: 'ironman',
    name: 'Iron Man',
    fullName: 'Tony Stark',
    avatar: '/assets/ironman-avatar.png',
    fullBody: '/assets/ironman-tarjeta.gif',
    description: 'Tony Stark es un genio, multimillonario, playboy y filántropo. Dueño de Stark Industries y creador de la armadura Iron Man. Miembro fundador de los Avengers.',
    accentColor: '#c62828',
    welcomeTitle: '¡Bienvenido al taller!',
    welcomeHint: 'Escribí tu primer mensaje para hablar con Iron Man.',
    typingText: 'Iron Man está escribiendo',
    bubbleIcon: '/assets/reactor.png',
  },
  capitan: {
    id: 'capitan',
    name: 'Captain America',
    fullName: 'Steve Rogers',
    avatar: '/assets/capitan-avatar.png',
    fullBody: '/assets/capitan-tarjeta.gif',
    description: 'Steve Rogers es el supersoldado que lucha por la justicia y la libertad. Líder nato y estratega de los Avengers. Siempre listo para defender a los inocentes.',
    accentColor: '#1565c0',
    welcomeTitle: '¡Bienvenido, soldado!',
    welcomeHint: 'Escribí tu primer mensaje para hablar con Captain America.',
    typingText: 'Captain America está escribiendo',
    bubbleIcon: '/assets/escudo.png',
  },
  spiderman: {
    id: 'spiderman',
    name: 'Spider-Man',
    fullName: 'Peter Parker',
    avatar: '/assets/spiderman-avatar.png',
    fullBody: '/assets/spiderman-tarjeta.gif',
    description: 'Peter Parker es tu amigable vecino Spider-Man. Con grandes poderes vienen grandes responsabilidades. El héroe más joven de los Avengers.',
    accentColor: '#d32f2f',
    welcomeTitle: '¡Bienvenido, amigazo!',
    welcomeHint: 'Escribí tu primer mensaje para hablar con Spider-Man.',
    typingText: 'Spider-Man está escribiendo',
    bubbleIcon: '/assets/arana.png',
  },
}
